### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by iiRevzz** [GeoFS-Autoland/autoland#2]
**Is your feature request related to a problem? If so, please explain.**
Yes, when you land, the throttle does not go down to zero, which makes the plane overrun the runway if you are not at your computer.

**What would you like added?**
Auto brakes, and auto reverse thrust.

**Are there alternatives you've considered? If so, please list them.**
No

**Comment by Featherway** [comment]
Hello! You will will have to manually idle your throttle on landing. However, that will be implemented in future releases. Autobrakes are also on the way to be released in future versions. I don't think auto reverse thrust will be added, since pilots always do it manually in real life, and it's not on our future plans. I hope that helps!

**Comment by nicolas377** [comment]
Thanks for submitting your request! Autobrakes will be implemented in 0.3-0, along with auto idle on landing. Automatic reverse thrust will not be implemented, because not every aircraft has reverse thrust available.
